version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - backend

